name: Checkout Deneme

on:
  push:
    branches:
      - checkout-deneme

jobs:
  dosya-listeleme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files
        run: ls -la